#!/usr/bin/env bash

set -euo pipefail

usage() {
  echo "Create a Python virtual environment with dependencies from requirements.txt"
  echo "Usage: $(basename "$0") <requirements.txt> <venv-dir>"
}

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

requirements="$1"
venv_dir="$2"

# Create virtual environment
mkdir -p "$venv_dir"
# Note: The --copies flag is important here because it tells venv to copy
# rather than symlink in library files, which is important for the virtual
# environment to function properly in a sandboxed Wake execution.
python3.7 -m venv --copies "$venv_dir"


# Activate virtual environment and have pip install packages from
# requirements.txt into the virtual environment
. "${venv_dir}/bin/activate"
pip install -r $requirements
